name: 'run'

on:
  schedule:
  - cron: '1 16 * * *'   # 北京时间 00:01
  - cron: '15 2 * * *'   # 北京时间 10:15
  - cron: '59 15 * * *'  # 北京时间 23:59
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.11
          

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:
          cookie_javbus: ${{ secrets.cookie_javbus }}
        run: |
          python3 ../javbus/javbus.py
          
